[[libgsd]]
arch = "aarch64"
git-tree-sha1 = "d4969cf95685c37204033b9615949e6865e1841a"
os = "macos"

    [[libgsd.download]]
    sha256 = "774b31cba435b67c0f6259dc1c9d969c2a10f84db09601058854a69da5122200"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.aarch64-apple-darwin.tar.gz"
[[libgsd]]
arch = "aarch64"
git-tree-sha1 = "d57b28cfbe0fbc3fcbfbb7ee6f325fa909644958"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "e65a934a4e53e56f7ab3cf3ec265f6650575cf8cc0303285e7ec1c62672b03de"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.aarch64-linux-gnu.tar.gz"
[[libgsd]]
arch = "aarch64"
git-tree-sha1 = "b9574737970d9679c2095549eaba7b7c1a0857cf"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "baa5af7b14da380247869ed5b727942e343d27f9c8450e541470a1fc9f5a90ae"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.aarch64-linux-musl.tar.gz"
[[libgsd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a90b248026694f7e9ed2190cbbe1fdd90cf44dde"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "024470c82eaa32373414cbe97018a2cb968b0b4532ea0785828158fa2e0885ff"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.armv6l-linux-gnueabihf.tar.gz"
[[libgsd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ff4572cbd4769247d67310d894d40911f985c6d"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "3feed973eb0a43b0f47a39aabddb952e10a7a9236c8b4a0dce6eb32da8784c12"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.armv6l-linux-musleabihf.tar.gz"
[[libgsd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ed5161bb1aac65ea7521180019dd53d218ebfe5"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "f1892bc50d17f83128e69a4d50c5f63081b7bae0517b4f88c100a6391a4d038a"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.armv7l-linux-gnueabihf.tar.gz"
[[libgsd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd101048bfb09696a6015ec5d3728fa1aa9431cd"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "32061790c9778aef8edb0e72c3b48f0584490ccb809f01592c66dd81be531b86"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.armv7l-linux-musleabihf.tar.gz"
[[libgsd]]
arch = "i686"
git-tree-sha1 = "22d253ff2db392fb5238b4583c8e11459e364f8d"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "259e214871f1f727bda27478a3e41a39b3c9b5ef9e0e7b282b3ac2a9a2a7ddcb"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.i686-linux-gnu.tar.gz"
[[libgsd]]
arch = "i686"
git-tree-sha1 = "558b2fe1bbaaa6ad8b080fe7588e3d280f9354b1"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "85a4191abf9b0a6592cdd771710d1c09311e4468f03725469b3ba52c51407cb5"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.i686-linux-musl.tar.gz"
[[libgsd]]
arch = "powerpc64le"
git-tree-sha1 = "3be2d5fb97bedff4db092ab9c6b2f132153007f3"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "f2243a1eb94a278237610594ddfe344d8b8af115a295ffbfd0310fd521f6bc23"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.powerpc64le-linux-gnu.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "0d2331a94a6b0971cd514fbfa2a4296894487d8b"
os = "macos"

    [[libgsd.download]]
    sha256 = "0f622ecd82263b7fa13c664af163a8b33cb47f74114143926fa1c732591f3fbf"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.x86_64-apple-darwin.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "72236006827d63ea070a2c34bbfced3ad5d994ae"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "e662ed17c73d6d18f808bbcef8a079195140cad71409770dd0a87519e5d42b9b"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.x86_64-linux-gnu.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "f9b76a2e2c34add5eebc520c367511f61c68b2b1"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "10c314ae80c06770407f7b03990f5ad3a6722ab0a3890d6ef8f3cfce7498e331"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.x86_64-linux-musl.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "5137928317ac71978fa664190d236a6c04f5ea7e"
os = "freebsd"

    [[libgsd.download]]
    sha256 = "49e4b4072b591382cacadb48716e9200e96ab574f086fa30b4fc1b2318a68bba"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+0/libgsd.v3.2.1.x86_64-unknown-freebsd.tar.gz"
