[[libgsd]]
arch = "aarch64"
git-tree-sha1 = "2c0d9a8871763c3814f61e7229e6ec4b0465f0f5"
os = "macos"

    [[libgsd.download]]
    sha256 = "ad3a1f7f4dcb3acc2ef5381f53af72e0782813d503da21192d2411a0434726dd"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.aarch64-apple-darwin.tar.gz"
[[libgsd]]
arch = "aarch64"
git-tree-sha1 = "dce133da2b18113ee2185e41dfa20e583298bf67"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "a334001e58fe703e03fceae64c0d99a31015a725ac0edb69682e268a6fc2bcec"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.aarch64-linux-gnu.tar.gz"
[[libgsd]]
arch = "aarch64"
git-tree-sha1 = "752b84d5bd5ccb3d3a38a6795f3ce0a41350af70"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "3157b6be3045dcd496acf498932e48a2a3b70206a6990b77009b44a5dbc81551"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.aarch64-linux-musl.tar.gz"
[[libgsd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a36a23448dbbd1e59eda56c362eab35e82f0e79"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "2923ef9001c1633943b7be21b8a1dbbd4b2ca9ef878dae895f557955bbc0f4f4"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.armv6l-linux-gnueabihf.tar.gz"
[[libgsd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1bae0c3832376c69114dbd5b2b1e22f92bd3220"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "f709c05bb76e3d0f9dfaa72d7af19196a076dc785a1eddaac5c8d92d57e8e704"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.armv6l-linux-musleabihf.tar.gz"
[[libgsd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c222fdb2d2362a664ca584e112991cb57bc0e6b"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "12f55792754271127ed80d8262646599d6326bed957427eafdb4b4a357a2c514"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.armv7l-linux-gnueabihf.tar.gz"
[[libgsd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a3cc60e1804d0b2dcd92f274290a2aa13536794"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "cbf4e643bd593957027b424cb74cefd5b6e1e1ea5efa721b8815a9a0e32c953d"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.armv7l-linux-musleabihf.tar.gz"
[[libgsd]]
arch = "i686"
git-tree-sha1 = "86272266361fa960bf5d376773890f8c898f788d"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "2e3f5285845975e2c518c2d30122fad3b9e24c3d685909962ffa87c736dbbaa2"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.i686-linux-gnu.tar.gz"
[[libgsd]]
arch = "i686"
git-tree-sha1 = "330812084a0f8d2ffad8ee57bb81f6f071cc9a2a"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "31f4b4efc8fd8d8da5e0d19cb4f9f71c8d7100ebffd2be146983792069137297"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.i686-linux-musl.tar.gz"
[[libgsd]]
arch = "powerpc64le"
git-tree-sha1 = "9082743f99115af8a0a1f2501f96cb7a310b9277"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "4480508d1fd4f467c535314dff3291d1535abb751dd76c6afd990ad6ba2e8e4f"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.powerpc64le-linux-gnu.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "5f6670cb1df97c4cf103c019445940b8b900fd4f"
os = "macos"

    [[libgsd.download]]
    sha256 = "d1c16ea25a886b5431c05b6f7749e32ba53ddbe1702082165d1e27e074d4b7b7"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.x86_64-apple-darwin.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "eecc389e7c1bc4804541c9a653a01d130f3c3cb2"
libc = "glibc"
os = "linux"

    [[libgsd.download]]
    sha256 = "3f2d066b20481364c378116eafaf75ba22ff196ce78219102bffac568c109cce"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.x86_64-linux-gnu.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "9e59b90f7924757b0477a557b2eed5dfc6d14f57"
libc = "musl"
os = "linux"

    [[libgsd.download]]
    sha256 = "4fb64cf7c2bee0be18f8655e755c9332ada4f89a4638ec90e580698363dfc806"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.x86_64-linux-musl.tar.gz"
[[libgsd]]
arch = "x86_64"
git-tree-sha1 = "49be8ec28164af9e3494ca55e16527b565064935"
os = "freebsd"

    [[libgsd.download]]
    sha256 = "2a21d3b344d4e39ac91c75c69ded12032a4ff54976201725ecb1f1372ec411d7"
    url = "https://github.com/JuliaBinaryWrappers/libgsd_jll.jl/releases/download/libgsd-v3.2.1+1/libgsd.v3.2.1.x86_64-unknown-freebsd.tar.gz"
