# Autogenerated wrapper script for libgsd_jll for armv6l-linux-gnueabihf
export gsd_h, libgsd

JLLWrappers.@generate_wrapper_header("libgsd")
JLLWrappers.@declare_file_product(gsd_h)
JLLWrappers.@declare_library_product(libgsd, "libgsd.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        gsd_h,
        "include/gsd.h",
    )

    JLLWrappers.@init_library_product(
        libgsd,
        "lib/libgsd.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
